### PR TITLE
First line edited from documentation.md

### PR DESCRIPTION
**Pull request by zenith4**
I used the master branch as the BASE and the devr as the COMPARE:

### CODE REVIEW

**Comment by cyrielo** [comment]
Alright seen, try to be more descriptive in your commit messages

**Comment by paulappz** [comment]
ok. seen

**Comment by oiseu2tall** [comment]
i ve pulled

**Comment by cyrielo** [comment]
All right since we all accept this changed, i'm merging this branch into the master now

**Pull request merged**
